alias sshdv='ssh dvdas001-dev3'
alias sshdas='ssh pexdas001-dev3'
alias sshdev='ssh pexdev001-dev3'
alias sshtestfiles='ssh gsgd@test-files.payment-express.net'
alias sshmq='ssh gsgmq001-dev3'

alias cd-='cd -'
alias cd..='cd ..'
alias cm='cvs -q commit'
alias cu='cvs -q update -dP'
alias vi='vim'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias up='cd ..'
alias upp='cd ../..'
alias uppp='cd ../../..'
alias upppp='cd ../../../..'
alias uppppp='cd ../../../../..'
alias gitfiles='git diff-tree --no-commit-id --name-only -r'

