alias cd-='cd -'
alias cd..='cd ..'
alias cm='cvs -q commit'
alias cu='cvs -q update -dP'
alias vi='vim'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias up='cd ..'
alias upp='cd ../..'
alias uppp='cd ../../..'
alias upppp='cd ../../../..'
alias uppppp='cd ../../../../..'
alias gitfiles='git diff-tree --no-commit-id --name-only -r'

